-- MySQL Script generated by MySQL Workbench
-- vie 13 may 2022 18:00:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `biblioteca_db` ;

-- -----------------------------------------------------
-- Schema biblioteca_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca_db` ;
USE `biblioteca_db` ;

-- -----------------------------------------------------
-- Table `biblioteca_db`.`libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca_db`.`libro` ;

CREATE TABLE IF NOT EXISTS `biblioteca_db`.`libro` (
  `id_libro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `editorial` VARCHAR(45) NULL,
  `Area` VARCHAR(45) NULL,
  PRIMARY KEY (`id_libro`),
  UNIQUE INDEX `idLibro_UNIQUE` (`id_libro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_db`.`autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca_db`.`autor` ;

CREATE TABLE IF NOT EXISTS `biblioteca_db`.`autor` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_autor`),
  UNIQUE INDEX `idAutor_UNIQUE` (`id_autor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_db`.`libro_autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca_db`.`libro_autor` ;

CREATE TABLE IF NOT EXISTS `biblioteca_db`.`libro_autor` (
  `id_libro` INT NOT NULL,
  `id_autor` INT NOT NULL,
  INDEX `fk_LibroAutor_Libro_idx` (`id_libro` ASC) VISIBLE,
  INDEX `fk_LibroAutor_Autor_idx` (`id_autor` ASC) VISIBLE,
  CONSTRAINT `fk_LibroAutor_Libro`
    FOREIGN KEY (`id_libro`)
    REFERENCES `biblioteca_db`.`libro` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LibroAutor_Autor`
    FOREIGN KEY (`id_autor`)
    REFERENCES `biblioteca_db`.`autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca_db`.`estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca_db`.`estudiante` ;

CREATE TABLE IF NOT EXISTS `biblioteca_db`.`estudiante` (
  `id_lector` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `carrera` VARCHAR(45) NULL,
  `edad` INT NULL,
  PRIMARY KEY (`id_lector`),
  UNIQUE INDEX `idLector_UNIQUE` (`id_lector` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `biblioteca_db`.`prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca_db`.`prestamo` ;

CREATE TABLE IF NOT EXISTS `biblioteca_db`.`prestamo` (
  `id_lector` INT NOT NULL,
  `id_libro` INT NOT NULL,
  `fecha_prestamo` DATETIME NOT NULL,
  `fecha_devolucion` DATETIME NULL,
  `devuelto` TINYINT NULL,
  INDEX `fk_Prestamo_Libro_idx` (`id_libro` ASC) VISIBLE,
  INDEX `fk_Prestamo_Estudiante_idx` (`id_lector` ASC) VISIBLE,
  CONSTRAINT `fk_Prestamo_Libro`
    FOREIGN KEY (`id_libro`)
    REFERENCES `biblioteca_db`.`libro` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_Estudiante`
    FOREIGN KEY (`id_lector`)
    REFERENCES `biblioteca_db`.`estudiante` (`id_lector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `biblioteca_db`.`libro`
-- -----------------------------------------------------
START TRANSACTION;
USE `biblioteca_db`;
INSERT INTO `biblioteca_db`.`libro` (`id_libro`, `titulo`, `editorial`, `Area`) VALUES (1, 'Harry postre', NULL, NULL);
INSERT INTO `biblioteca_db`.`libro` (`id_libro`, `titulo`, `editorial`, `Area`) VALUES (2, 'Harry postre 2', NULL, NULL);
INSERT INTO `biblioteca_db`.`libro` (`id_libro`, `titulo`, `editorial`, `Area`) VALUES (3, 'Harry postre 3: La venganza de Harry', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `biblioteca_db`.`autor`
-- -----------------------------------------------------
START TRANSACTION;
USE `biblioteca_db`;
INSERT INTO `biblioteca_db`.`autor` (`id_autor`, `nombre`, `nacionalidad`) VALUES (DEFAULT, 'Maria', 'Argentina');

COMMIT;


-- -----------------------------------------------------
-- Data for table `biblioteca_db`.`libro_autor`
-- -----------------------------------------------------
START TRANSACTION;
USE `biblioteca_db`;
INSERT INTO `biblioteca_db`.`libro_autor` (`id_libro`, `id_autor`) VALUES (1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `biblioteca_db`.`estudiante`
-- -----------------------------------------------------
START TRANSACTION;
USE `biblioteca_db`;
INSERT INTO `biblioteca_db`.`estudiante` (`id_lector`, `nombre`, `apellido`, `direccion`, `carrera`, `edad`) VALUES (DEFAULT, 'Juan', 'Carlos', NULL, NULL, NULL);
INSERT INTO `biblioteca_db`.`estudiante` (`id_lector`, `nombre`, `apellido`, `direccion`, `carrera`, `edad`) VALUES (DEFAULT, 'Saul', 'Menem', NULL, NULL, NULL);
INSERT INTO `biblioteca_db`.`estudiante` (`id_lector`, `nombre`, `apellido`, `direccion`, `carrera`, `edad`) VALUES (DEFAULT, 'Agus', 'Legui', NULL, NULL, NULL);
INSERT INTO `biblioteca_db`.`estudiante` (`id_lector`, `nombre`, `apellido`, `direccion`, `carrera`, `edad`) VALUES (DEFAULT, 'Pedro', 'Sanchez', NULL, NULL, NULL);
INSERT INTO `biblioteca_db`.`estudiante` (`id_lector`, `nombre`, `apellido`, `direccion`, `carrera`, `edad`) VALUES (DEFAULT, 'Pablo', 'Juarez', NULL, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `biblioteca_db`.`prestamo`
-- -----------------------------------------------------
START TRANSACTION;
USE `biblioteca_db`;
INSERT INTO `biblioteca_db`.`prestamo` (`id_lector`, `id_libro`, `fecha_prestamo`, `fecha_devolucion`, `devuelto`) VALUES (1, 1, '2022-05-10', '2022-05-15', NULL);
INSERT INTO `biblioteca_db`.`prestamo` (`id_lector`, `id_libro`, `fecha_prestamo`, `fecha_devolucion`, `devuelto`) VALUES (1, 2, '2022-05-07', NULL, NULL);
INSERT INTO `biblioteca_db`.`prestamo` (`id_lector`, `id_libro`, `fecha_prestamo`, `fecha_devolucion`, `devuelto`) VALUES (2, 2, '2022-05-07', '2022-05-09', NULL);
INSERT INTO `biblioteca_db`.`prestamo` (`id_lector`, `id_libro`, `fecha_prestamo`, `fecha_devolucion`, `devuelto`) VALUES (3, 2, '2022-05-07', '2022-05-09', NULL);
INSERT INTO `biblioteca_db`.`prestamo` (`id_lector`, `id_libro`, `fecha_prestamo`, `fecha_devolucion`, `devuelto`) VALUES (4, 3, '2022-05-07', NULL, NULL);

COMMIT;

